/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.emergencyvehicle.view;

import com.emergencyvehicle.controller.algorithms.SelectionSort;
import com.emergencyvehicle.controller.algorithms.InsertionSort;
import com.emergencyvehicle.controller.algorithms.MergeSort;

import com.emergencyvehicle.controller.datastructure.VehicleManager;
import com.emergencyvehicle.util.ValidationUtil;
import com.emergencyvehicle.model.EmergencyVehicle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.emergencyvehicle.model.EmergencyService;
import com.emergencyvehicle.controller.datastructure.CustomQueue;


public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
    initComponents();// Initialize all GUI components
    this.setLocationRelativeTo(null);
    btnUpdateVehicle.setEnabled(false);// At first Update button s disabled

    // Set the DefaultTableModel for the table
    DefaultTableModel tableModel = new DefaultTableModel(
        new Object[][]{}, // Initial data (empty)
        new String[]{"Serial Number", "Model Name", "Vehicle Number", "Vehicle Type", "Availability Status", "Current Location", "Price","Service Request","Dispatched Vehicle"} // Column names
        
    );
    tblEmergencyVehicles.setModel(tableModel); // Attach the model to the table
    populateVehicleTable(); // Populate the table with vehicle data
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbAdminDashBoard = new javax.swing.JTabbedPane();
        pnlAboutUs = new javax.swing.JPanel();
        SpAboutus = new javax.swing.JScrollPane();
        TAAboutUS = new javax.swing.JTextArea();
        lblAbout = new javax.swing.JLabel();
        lblAbouta = new javax.swing.JLabel();
        lblAboutUsLogo = new javax.swing.JLabel();
        pnlhome = new javax.swing.JPanel();
        pnlAmbulance = new javax.swing.JPanel();
        lblNumberAmbulance = new javax.swing.JLabel();
        lblAmbulanceNumber = new javax.swing.JLabel();
        lblAvailableAmbulance = new javax.swing.JLabel();
        pnlFirefighters = new javax.swing.JPanel();
        lblNumberFirefightersAvailable = new javax.swing.JLabel();
        lblFirefightersNumber = new javax.swing.JLabel();
        lblAvailableFire = new javax.swing.JLabel();
        pnlPoliceCars = new javax.swing.JPanel();
        lblSlogan = new javax.swing.JLabel();
        lblFireTruck1 = new javax.swing.JLabel();
        lblAmbulance2 = new javax.swing.JLabel();
        lblAmbulance1 = new javax.swing.JLabel();
        lblPoliceCar1 = new javax.swing.JLabel();
        lblPoliceCar2 = new javax.swing.JLabel();
        lblFireTruck2 = new javax.swing.JLabel();
        pnlAmbulance1 = new javax.swing.JPanel();
        pnlAmbulance2 = new javax.swing.JPanel();
        lblNumberAmbulance2 = new javax.swing.JLabel();
        lblAmbulanceNumber2 = new javax.swing.JLabel();
        lblAvailableAmbulance2 = new javax.swing.JLabel();
        pnlPoliceCars1 = new javax.swing.JPanel();
        lblNumberPoliceCarsAvailable1 = new javax.swing.JLabel();
        lblNumberPoliceAvailable1 = new javax.swing.JLabel();
        lblAvailablePolice2 = new javax.swing.JLabel();
        lblNumberPoliceCarsAvailable = new javax.swing.JLabel();
        lblNumberPoliceAvailable = new javax.swing.JLabel();
        lblAvailablePolice1 = new javax.swing.JLabel();
        lblNumberAmbulance1 = new javax.swing.JLabel();
        lblAmbulanceNumber1 = new javax.swing.JLabel();
        lblAvailableAmbulance1 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        lblSerialNumber = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        tfSerialNumber = new javax.swing.JTextField();
        lblEmergencyVehicleName = new javax.swing.JLabel();
        lblVehicleType = new javax.swing.JLabel();
        lblAvailabilityStatus = new javax.swing.JLabel();
        lblCurrentLocation = new javax.swing.JLabel();
        tfModelNumber = new javax.swing.JTextField();
        tfEmergencyVehicleName = new javax.swing.JTextField();
        cbVehicleType = new javax.swing.JComboBox<>();
        tfPrice = new javax.swing.JTextField();
        cbAvailabilityStatus = new javax.swing.JComboBox<>();
        btnAddVehicle = new javax.swing.JButton();
        btnDeleteVehicle = new javax.swing.JButton();
        cbLocation = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmergencyVehicles = new javax.swing.JTable();
        btnUpdateVehicle = new javax.swing.JButton();
        btnFetch = new javax.swing.JButton();
        pnlSortingPart = new javax.swing.JPanel();
        lblSortingPart = new javax.swing.JLabel();
        btnSortByVehicleName = new javax.swing.JButton();
        btSort = new javax.swing.JButton();
        btnSortByModelName = new javax.swing.JButton();
        PnlServiceRequest = new javax.swing.JPanel();
        lnlServiceRequest = new javax.swing.JLabel();
        tfServiceRequest = new javax.swing.JTextField();
        btnDispatchVehicle = new javax.swing.JButton();
        btnAddServiceRequest = new javax.swing.JButton();
        tfDispatchVehicle = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfEmergencyCalls = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfEmail = new javax.swing.JTextArea();
        lblSearch = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        pnlheader = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblEmergencyVehicleIS = new javax.swing.JLabel();
        lblSmallLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbAdminDashBoard.setBackground(new java.awt.Color(204, 255, 255));

        pnlAboutUs.setBackground(new java.awt.Color(204, 204, 255));
        pnlAboutUs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TAAboutUS.setBackground(new java.awt.Color(204, 204, 255));
        TAAboutUS.setColumns(20);
        TAAboutUS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TAAboutUS.setRows(5);
        TAAboutUS.setText("\nIn today's fast-paced world, timely and efficient emergency response can save countless lives.At EVIS, we aim to revolutionize \nthe way emergency vehicles operate by providing a cutting-edge, centralized system for managing and monitoring emergency \nfleet operations.With real-time tracking, seamless communication, and intelligent dispatching, our platform ensures emergency \nvehicles reach their destinations faster and more effectively.By leveraging the latest in technology, EVIS plays a critical role in reducing\nresponse times and improving outcomes for emergency situations.By harnessing the power of cutting-edge technology,\nEVIS is at the forefront of revolutionizing emergency response systems, ultimately contributing to safer and more resilient communities. \nThis commitment to excellence and innovation positions EVIS as a critical player in improving outcomes for emergencies worldwide\nBy harnessing the power of cutting-edge technology, EVIS is at the forefront of revolutionizing emergency response systems, ultimately\ncontributing to safer and more resilient communities. This commitment to excellence and innovation positions EVIS as a critical player in \nimproving outcomes for emergencies worldwide. Through our relentless focus on innovation and efficiency, we aim to set new standards\nin emergency vehicle operations, ensuring that help is always just around the corner.\n\n\nJoin us in creating safer communities through innovation and dedication.\n");
        SpAboutus.setViewportView(TAAboutUS);

        pnlAboutUs.add(SpAboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 890, 350));

        lblAbout.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAbout.setText("About Us");
        pnlAboutUs.add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 50));

        lblAbouta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAbouta.setText("Reliable, Innovative, and Swift Emergency Response Solution");
        pnlAboutUs.add(lblAbouta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 530, -1));

        lblAboutUsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/rb_68108 (2).png"))); // NOI18N
        pnlAboutUs.add(lblAboutUsLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 440, -1));

        tbAdminDashBoard.addTab("AboutUs", pnlAboutUs);

        pnlhome.setBackground(new java.awt.Color(204, 204, 255));

        pnlAmbulance.setBackground(new java.awt.Color(204, 204, 255));

        lblNumberAmbulance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberAmbulance.setText("Ambulance Model : A100");

        lblAmbulanceNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAmbulanceNumber.setText("Status:");

        lblAvailableAmbulance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailableAmbulance.setText("Available ");

        javax.swing.GroupLayout pnlAmbulanceLayout = new javax.swing.GroupLayout(pnlAmbulance);
        pnlAmbulance.setLayout(pnlAmbulanceLayout);
        pnlAmbulanceLayout.setHorizontalGroup(
            pnlAmbulanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmbulanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAmbulanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAmbulanceLayout.createSequentialGroup()
                        .addComponent(lblAmbulanceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAvailableAmbulance))
                    .addComponent(lblNumberAmbulance))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnlAmbulanceLayout.setVerticalGroup(
            pnlAmbulanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmbulanceLayout.createSequentialGroup()
                .addComponent(lblNumberAmbulance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAmbulanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailableAmbulance)
                    .addComponent(lblAmbulanceNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFirefighters.setBackground(new java.awt.Color(204, 204, 255));

        lblNumberFirefightersAvailable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberFirefightersAvailable.setText("Firefighter Model : F200");

        lblFirefightersNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFirefightersNumber.setText("Status:");

        lblAvailableFire.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailableFire.setText("Unavailable");

        javax.swing.GroupLayout pnlFirefightersLayout = new javax.swing.GroupLayout(pnlFirefighters);
        pnlFirefighters.setLayout(pnlFirefightersLayout);
        pnlFirefightersLayout.setHorizontalGroup(
            pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirefightersLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFirefightersLayout.createSequentialGroup()
                        .addComponent(lblFirefightersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvailableFire, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNumberFirefightersAvailable))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        pnlFirefightersLayout.setVerticalGroup(
            pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirefightersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumberFirefightersAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFirefightersNumber)
                    .addComponent(lblAvailableFire, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlPoliceCars.setBackground(new java.awt.Color(204, 204, 255));
        pnlPoliceCars.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlPoliceCarsLayout = new javax.swing.GroupLayout(pnlPoliceCars);
        pnlPoliceCars.setLayout(pnlPoliceCarsLayout);
        pnlPoliceCarsLayout.setHorizontalGroup(
            pnlPoliceCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        pnlPoliceCarsLayout.setVerticalGroup(
            pnlPoliceCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        lblSlogan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSlogan.setText("Responding Fast, Saving Lives");

        lblFireTruck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/firetruck1-removebg-preview.png"))); // NOI18N

        lblAmbulance2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/ambulancea-removebg-preview.png"))); // NOI18N

        lblAmbulance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/ambulance2__1_-removebg-preview.png"))); // NOI18N

        lblPoliceCar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/policecar2-removebg-preview.png"))); // NOI18N

        lblPoliceCar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/policecar1-removebg-preview.png"))); // NOI18N
        lblPoliceCar2.setText("jLabel3");

        lblFireTruck2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/firetruck2-removebg-preview.png"))); // NOI18N
        lblFireTruck2.setText("jLabel3");

        pnlAmbulance1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout pnlAmbulance1Layout = new javax.swing.GroupLayout(pnlAmbulance1);
        pnlAmbulance1.setLayout(pnlAmbulance1Layout);
        pnlAmbulance1Layout.setHorizontalGroup(
            pnlAmbulance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pnlAmbulance1Layout.setVerticalGroup(
            pnlAmbulance1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlAmbulance2.setBackground(new java.awt.Color(204, 204, 255));

        lblNumberAmbulance2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberAmbulance2.setText("Firefighter Model : F250");

        lblAmbulanceNumber2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAmbulanceNumber2.setText("Status:");

        lblAvailableAmbulance2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailableAmbulance2.setText("Unavailable ");

        javax.swing.GroupLayout pnlAmbulance2Layout = new javax.swing.GroupLayout(pnlAmbulance2);
        pnlAmbulance2.setLayout(pnlAmbulance2Layout);
        pnlAmbulance2Layout.setHorizontalGroup(
            pnlAmbulance2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmbulance2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlAmbulance2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberAmbulance2)
                    .addGroup(pnlAmbulance2Layout.createSequentialGroup()
                        .addComponent(lblAmbulanceNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAvailableAmbulance2)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        pnlAmbulance2Layout.setVerticalGroup(
            pnlAmbulance2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmbulance2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblNumberAmbulance2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAmbulance2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailableAmbulance2)
                    .addComponent(lblAmbulanceNumber2))
                .addContainerGap())
        );

        pnlPoliceCars1.setBackground(new java.awt.Color(204, 204, 255));
        pnlPoliceCars1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlPoliceCars1Layout = new javax.swing.GroupLayout(pnlPoliceCars1);
        pnlPoliceCars1.setLayout(pnlPoliceCars1Layout);
        pnlPoliceCars1Layout.setHorizontalGroup(
            pnlPoliceCars1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlPoliceCars1Layout.setVerticalGroup(
            pnlPoliceCars1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        lblNumberPoliceCarsAvailable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberPoliceCarsAvailable1.setText("Police Car Model : P350");

        lblNumberPoliceAvailable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberPoliceAvailable1.setText("Status:");

        lblAvailablePolice2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailablePolice2.setText("UnAvailable ");

        lblNumberPoliceCarsAvailable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberPoliceCarsAvailable.setText("Police Car Model : P300");

        lblNumberPoliceAvailable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberPoliceAvailable.setText("Status:");

        lblAvailablePolice1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailablePolice1.setText("Available ");

        lblNumberAmbulance1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberAmbulance1.setText("Ambulance Model : A150");

        lblAmbulanceNumber1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAmbulanceNumber1.setText("Status:");

        lblAvailableAmbulance1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailableAmbulance1.setText("Available ");

        javax.swing.GroupLayout pnlhomeLayout = new javax.swing.GroupLayout(pnlhome);
        pnlhome.setLayout(pnlhomeLayout);
        pnlhomeLayout.setHorizontalGroup(
            pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhomeLayout.createSequentialGroup()
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlAmbulance2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlFirefighters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblFireTruck2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFireTruck1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmbulance1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlhomeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlhomeLayout.createSequentialGroup()
                                        .addComponent(lblAmbulanceNumber1)
                                        .addGap(37, 37, 37)
                                        .addComponent(lblAvailableAmbulance1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pnlAmbulance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNumberAmbulance1)))))
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(lblAmbulance2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlPoliceCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlPoliceCars1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlhomeLayout.createSequentialGroup()
                                .addComponent(lblNumberPoliceAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAvailablePolice1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNumberPoliceCarsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhomeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlhomeLayout.createSequentialGroup()
                                .addComponent(lblNumberPoliceAvailable1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAvailablePolice2))
                            .addComponent(lblNumberPoliceCarsAvailable1))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPoliceCar2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPoliceCar1))
                        .addGap(20, 20, 20))))
            .addGroup(pnlhomeLayout.createSequentialGroup()
                .addGap(504, 504, 504)
                .addComponent(lblSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlhomeLayout.setVerticalGroup(
            pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhomeLayout.createSequentialGroup()
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addComponent(lblSlogan)
                        .addGap(12, 12, 12)
                        .addComponent(lblAmbulance2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPoliceCar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFireTruck1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPoliceCar1)
                            .addGroup(pnlhomeLayout.createSequentialGroup()
                                .addComponent(pnlAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lblAmbulance1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumberAmbulance1)
                            .addComponent(lblNumberPoliceCarsAvailable1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlAmbulance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlhomeLayout.createSequentialGroup()
                                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNumberPoliceAvailable1)
                                        .addComponent(lblAvailablePolice2))
                                    .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblAvailableAmbulance1)
                                        .addComponent(lblAmbulanceNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 19, Short.MAX_VALUE))))
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlhomeLayout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(pnlAmbulance2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlhomeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlhomeLayout.createSequentialGroup()
                                        .addComponent(lblNumberPoliceCarsAvailable)
                                        .addGap(4, 4, 4)
                                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblNumberPoliceAvailable)
                                            .addComponent(lblAvailablePolice1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnlPoliceCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlhomeLayout.createSequentialGroup()
                                        .addComponent(pnlFirefighters, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(lblFireTruck2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPoliceCars1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        tbAdminDashBoard.addTab("Homepage", pnlhome);

        pnlAdmin.setBackground(new java.awt.Color(204, 204, 255));

        lblSerialNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSerialNumber.setText("Serial Number");

        lblModelNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblModelNumber.setText("Model Name");

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setText("Price");

        lblEmergencyVehicleName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmergencyVehicleName.setText("Vehicle Number");

        lblVehicleType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVehicleType.setText("Vehicle Type");

        lblAvailabilityStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAvailabilityStatus.setText("Availability Status");

        lblCurrentLocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCurrentLocation.setText("Current Location");

        tfModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModelNumberActionPerformed(evt);
            }
        });

        cbVehicleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulance", "Fire Truck", "Police Car" }));

        cbAvailabilityStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));

        btnAddVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddVehicle.setText("Add Vehicle");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        btnDeleteVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteVehicle.setText("Delete Vehicle");
        btnDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVehicleActionPerformed(evt);
            }
        });

        cbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manamaiju", "Kamalpokhari", "Baneshwor", "Ratnapark", "Gongabu", "Basundhara", "Thamel" }));

        tblEmergencyVehicles.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tblEmergencyVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial Number", "Model Number", "Vehicle Name", "Vehicle Type", "Price", "Availability Status", "Current Location", "Service request", "Dispatched Vehicles"
            }
        ));
        jScrollPane1.setViewportView(tblEmergencyVehicles);

        btnUpdateVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateVehicle.setText("Update Vehicles");
        btnUpdateVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVehicleActionPerformed(evt);
            }
        });

        btnFetch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFetch.setText("Fetch");
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });

        pnlSortingPart.setBackground(new java.awt.Color(204, 255, 255));

        lblSortingPart.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblSortingPart.setText("Sorting Section");

        btnSortByVehicleName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSortByVehicleName.setText("Sort By Vehicle Number");
        btnSortByVehicleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByVehicleNameActionPerformed(evt);
            }
        });

        btSort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSort.setText("Sort By Serial Number");
        btSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortActionPerformed(evt);
            }
        });

        btnSortByModelName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSortByModelName.setText("Sort By Model Name");
        btnSortByModelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByModelNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSortingPartLayout = new javax.swing.GroupLayout(pnlSortingPart);
        pnlSortingPart.setLayout(pnlSortingPartLayout);
        pnlSortingPartLayout.setHorizontalGroup(
            pnlSortingPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSortingPartLayout.createSequentialGroup()
                .addGroup(pnlSortingPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSortByVehicleName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSortingPartLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSortingPart, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addComponent(btnSortByModelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btSort, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pnlSortingPartLayout.setVerticalGroup(
            pnlSortingPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSortingPartLayout.createSequentialGroup()
                .addComponent(lblSortingPart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(pnlSortingPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortByVehicleName)
                    .addComponent(btnSortByModelName)
                    .addComponent(btSort))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PnlServiceRequest.setBackground(new java.awt.Color(204, 255, 204));

        lnlServiceRequest.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lnlServiceRequest.setText("Section For Service Request And Dispatch Vehicles");

        tfServiceRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfServiceRequestActionPerformed(evt);
            }
        });

        btnDispatchVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDispatchVehicle.setText("Dispatch Vehicles");
        btnDispatchVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDispatchVehicleActionPerformed(evt);
            }
        });

        btnAddServiceRequest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddServiceRequest.setText("Service Request");
        btnAddServiceRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlServiceRequestLayout = new javax.swing.GroupLayout(PnlServiceRequest);
        PnlServiceRequest.setLayout(PnlServiceRequestLayout);
        PnlServiceRequestLayout.setHorizontalGroup(
            PnlServiceRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlServiceRequestLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PnlServiceRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnlServiceRequest)
                    .addGroup(PnlServiceRequestLayout.createSequentialGroup()
                        .addGroup(PnlServiceRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfServiceRequest, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddServiceRequest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(PnlServiceRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDispatchVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfDispatchVehicle))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlServiceRequestLayout.setVerticalGroup(
            PnlServiceRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlServiceRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lnlServiceRequest)
                .addGap(45, 45, 45)
                .addGroup(PnlServiceRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfServiceRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDispatchVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlServiceRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDispatchVehicle)
                    .addComponent(btnAddServiceRequest))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tfEmergencyCalls.setColumns(20);
        tfEmergencyCalls.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfEmergencyCalls.setRows(5);
        tfEmergencyCalls.setText("Number of Emergency calls Received\n\n                        140\n\n         17% up since last month");
        jScrollPane2.setViewportView(tfEmergencyCalls);

        tfEmail.setColumns(20);
        tfEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfEmail.setRows(5);
        tfEmail.setText("                Email  Messages\n\n                        100\n\n         12% up since last month");
        jScrollPane3.setViewportView(tfEmail);

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSearch.setText("Search Bar");

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addComponent(pnlSortingPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlServiceRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAdminLayout.createSequentialGroup()
                                        .addComponent(btnAddVehicle)
                                        .addGap(69, 69, 69)
                                        .addComponent(btnFetch)
                                        .addGap(75, 75, 75)
                                        .addComponent(btnUpdateVehicle)
                                        .addGap(66, 66, 66)
                                        .addComponent(btnDeleteVehicle))
                                    .addGroup(pnlAdminLayout.createSequentialGroup()
                                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                                .addComponent(lblSerialNumber)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblModelNumber))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                                                .addComponent(tfSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(tfEmergencyVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)))
                                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                                .addComponent(lblEmergencyVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(lblVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                                .addComponent(tfModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(68, 68, 68))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(80, 80, 80)))
                                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAvailabilityStatus)
                                            .addComponent(cbAvailabilityStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)
                                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCurrentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addGap(379, 379, 379)
                                .addComponent(lblSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(193, 193, 193))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearch)
                            .addComponent(btnSearch)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurrentLocation)
                            .addComponent(lblAvailabilityStatus)
                            .addComponent(lblPrice)
                            .addComponent(lblVehicleType)
                            .addComponent(lblEmergencyVehicleName)
                            .addComponent(lblModelNumber)
                            .addComponent(lblSerialNumber))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmergencyVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAvailabilityStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddVehicle)
                            .addComponent(btnFetch)
                            .addComponent(btnUpdateVehicle)
                            .addComponent(btnDeleteVehicle))
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSortingPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlServiceRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tbAdminDashBoard.addTab("Admin Dashboard", pnlAdmin);

        pnlheader.setBackground(new java.awt.Color(255, 255, 255));

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblEmergencyVehicleIS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEmergencyVehicleIS.setForeground(new java.awt.Color(255, 0, 0));
        lblEmergencyVehicleIS.setText("Emergency Vehicle Information System");

        lblSmallLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/Actualsmallambulance.png"))); // NOI18N

        javax.swing.GroupLayout pnlheaderLayout = new javax.swing.GroupLayout(pnlheader);
        pnlheader.setLayout(pnlheaderLayout);
        pnlheaderLayout.setHorizontalGroup(
            pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlheaderLayout.createSequentialGroup()
                .addComponent(lblSmallLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(lblEmergencyVehicleIS)
                .addGap(325, 325, 325)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        pnlheaderLayout.setVerticalGroup(
            pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSmallLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
            .addGroup(pnlheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlheaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmergencyVehicleIS)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlheader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbAdminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbAdminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
                logoutAction();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tfServiceRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfServiceRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfServiceRequestActionPerformed
     
    private EmergencyService emergencyService = new EmergencyService();// Instance of EmergencyService to manage service requests
    private List<EmergencyVehicle> emergencyVehicles = new ArrayList<>();// List to store emergency vehicles

/** 
 * Populates the vehicle table with data from the emergency vehicles list and service requests.
 */
    

private void populateVehicleTable() {
    // Get the DefaultTableModel from the table
    DefaultTableModel tableModel = (DefaultTableModel) tblEmergencyVehicles.getModel();
    tableModel.setRowCount(0); // Clear existing data

    for (EmergencyVehicle vehicle : VehicleManager.getEmergencyVehicles()) {
        tableModel.addRow(new Object[]{
            vehicle.getSerialNumber(),
            vehicle.getEmergencyVehicleName(),
            vehicle.getModelNumber(),
            vehicle.getVehicleType(),
            vehicle.getAvailabilityStatus(),
            vehicle.getCurrentLocation(),
            vehicle.getPrice(),
            "", // Placeholder for service request
            vehicle.isDispatched() ? "Dispatched" : "Undispatched" // Populate dispatch status
        });
    }

    // Populate the service request column
    CustomQueue<String> serviceRequests = emergencyService.getServiceRequests();
    int rowIndex = 0;
    for (String request : serviceRequests) {
        tableModel.setValueAt(request, rowIndex++, 7); // Assuming column 7 is for service requests
    }
}



/**
 * Method to create an EmergencyVehicle object using user inputs and collect all error messages in a StringBuilder. 
 * This method retrieves user inputs, validates them, collects error messages, and creates an EmergencyVehicle object if all inputs are valid.
 * @return an EmergencyVehicle object if all inputs are valid
 * @throws IllegalArgumentException if there are validation errors
 */
private EmergencyVehicle createEmergencyVehicleFromInputs() {
    // Initializing a StringBuilder to collect all error messages
    StringBuilder errorMessages = new StringBuilder();

    // Get inputs from text fields
    String serialNumberText = tfSerialNumber.getText().trim();
    String modelNumber = tfModelNumber.getText().trim();
    String emergencyVehicleName = tfEmergencyVehicleName.getText().trim(); 
    String priceText = tfPrice.getText().trim();

    // Fetch vehicle type from the combo box
    String vehicleType = (String) cbVehicleType.getSelectedItem();

    // Validate vehicle type
    String vehicleTypeError = ValidationUtil.validateEmergencyVehicleType(cbVehicleType);
    if (vehicleTypeError != null) {
        errorMessages.append(vehicleTypeError).append("\n");
    }

    // Fetch location from the combo box
    String location = (String) cbLocation.getSelectedItem();

    // Validate location
    String locationError = ValidationUtil.validateLocation(cbLocation);
    if (locationError != null) {
        errorMessages.append(locationError).append("\n");
    }

    // Fetch availability status from the combo box
    String availabilityStatus = (String) cbAvailabilityStatus.getSelectedItem();

    // Validate availability status
    String availabilityStatusError = ValidationUtil.validateAvailabilityStatus(cbAvailabilityStatus);
    if (availabilityStatusError != null) {
        errorMessages.append(availabilityStatusError).append("\n");
    }

    // Validate serial number
    String serialValidationError = ValidationUtil.validateSerialNumber(serialNumberText);
    if (serialValidationError != null) {
        errorMessages.append(serialValidationError).append("\n");
    }

    // Validate model number
    String modelNumberError = ValidationUtil.validateModelNumber(modelNumber);
    if (modelNumberError != null) {
        errorMessages.append(modelNumberError).append("\n");
    }

    // Validate vehicle name
    String vehicleNameError = ValidationUtil.validateVehicleName(emergencyVehicleName);
    if (vehicleNameError != null) {
        errorMessages.append(vehicleNameError).append("\n");
    }

    // Validate price
    String priceValidationError = ValidationUtil.validatePrice(priceText);
    if (priceValidationError != null) {
        errorMessages.append(priceValidationError).append("\n");
    }

    // If there are any validation errors, show all messages and return null
    if (errorMessages.length() > 0) {
        throw new IllegalArgumentException(errorMessages.toString());
    }

    // Parse validated inputs
    int serialNumber = Integer.parseInt(serialNumberText);
    int price = Integer.parseInt(priceText);

    // Create and return the Emergency Vehicle object
    return new EmergencyVehicle(serialNumber, modelNumber, emergencyVehicleName, vehicleType, availabilityStatus, location, price,false);
}
    
//Method to clear all the textfields and reset the combobox
private void clearInputFields() {
    // Clear all text fields
    tfSerialNumber.setText("");
    tfModelNumber.setText("");
    tfEmergencyVehicleName.setText("");
    tfPrice.setText("");

    // Reset combo boxes to the first item (assuming the first item is a placeholder)
    cbVehicleType.setSelectedIndex(0);  
    cbAvailabilityStatus.setSelectedIndex(0); 
    cbLocation.setSelectedIndex(0);
}

/**
 * Method to add the vehicle information to the array list.
 * This method collects validation errors, creates an EmergencyVehicle object from user inputs, checks for duplicates,
 * and adds the vehicle to the list if all validations pass.
 * @param evt the action event triggered by the button click
 */
    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
    // Collect all validation errors at once
    StringBuilder errorMessages = new StringBuilder();

    EmergencyVehicle newVehicle = null; // Initialize the vehicle object
    try {
        newVehicle = createEmergencyVehicleFromInputs();
    } catch (IllegalArgumentException e) {
        // Append the specific error message from createEmergencyVehicleFromInputs
        errorMessages.append(e.getMessage()).append("\n");
    }

    // If there are errors or the vehicle is null, show them and stop execution
    if (errorMessages.length() > 0 || newVehicle == null) {
        JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.WARNING_MESSAGE);
        return; // Stop further execution
    }

    // Check for duplicate serial numbers
    for (EmergencyVehicle ev : VehicleManager.getEmergencyVehicles()) { 
        if (ev.getSerialNumber() == newVehicle.getSerialNumber()) {
            // Append an error message for duplicate serial number
            errorMessages.append("A vehicle with serial number ").append(newVehicle.getSerialNumber()).append(" already exists.\n");
            break; // Exit the loop once a duplicate is found
        }
    }

    // If there are errors after serial number check, show them and stop execution
    if (errorMessages.length() > 0) {
        JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.WARNING_MESSAGE);
        return; // Stop further execution
    }

    // Proceed to add the vehicle only if all validations pass
    try {
        VehicleManager.addVehicle(newVehicle);

        // Clear the input fields after successful addition
        clearInputFields();

        // Optionally, show a success message
        JOptionPane.showMessageDialog(null, "Emergency Vehicle Added Successfully!");
        populateVehicleTable();
    } catch (Exception ex) {
        // Handle unexpected errors during addition
        JOptionPane.showMessageDialog(null, "An error occurred while adding the vehicle: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    
    }    }//GEN-LAST:event_btnAddVehicleActionPerformed


/**
 * Method to delete the vehicle information.
 * This method deletes a vehicle from the array list based on the serial number entered by the user.
 * It validates the input, checks if the vehicle exists, and updates the table accordingly.
 *
 * @param evt the action event triggered by the button click
 */
    
    private void btnDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVehicleActionPerformed
    String serialNumberInput = tfSerialNumber.getText().trim(); // Get the input from the user

    if (serialNumberInput.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the serial number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int serialNumber = Integer.parseInt(serialNumberInput); // Convert to integer

        boolean isDeleted = VehicleManager.deleteVehicle(serialNumber); // Delete vehicle from the ArrayList

        if (isDeleted) {
            // Refresh the table to reflect the deletion
            populateVehicleTable();

            JOptionPane.showMessageDialog(this, "Vehicle deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearInputFields(); // Clear the input fields
        } else {
            JOptionPane.showMessageDialog(this, "Vehicle not found. Please check the serial number.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid serial number. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_btnDeleteVehicleActionPerformed

/**
 * Method to update the vehicle information according to the serial number. 
 * This method validates the user inputs, creates an EmergencyVehicle object, finds and updates the vehicle in the ArrayList,
 * refreshes the table, and displays appropriate messages.
 *
 * @param evt the action event triggered by the button click
 */
    private void btnUpdateVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVehicleActionPerformed
try {
        // Validate and create a new EmergencyVehicle object from inputs
        EmergencyVehicle updatedVehicle = createEmergencyVehicleFromInputs();

        // Find and update the vehicle in the ArrayList
        boolean isUpdated = VehicleManager.updateVehicle(updatedVehicle);

        if (isUpdated) {
            // Refresh the table
            populateVehicleTable();

            JOptionPane.showMessageDialog(this, "Vehicle details updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearInputFields(); // Clear the input fields
            btnUpdateVehicle.setEnabled(false); // Disable update button
        } else {
            JOptionPane.showMessageDialog(this, "Vehicle not found. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Validation Errors", JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_btnUpdateVehicleActionPerformed

/**
 * Method to fetch the vehicle data to edit.
 
 * This method retrieves the vehicle data based on the serial number entered by the user,
 * populates the input fields with the vehicle's details, and enables the update button.
 *
 * @param evt the action event triggered by the button click
 */

    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed
    String serialNumberInput = tfSerialNumber.getText().trim(); // Get the serial number input

    if (serialNumberInput.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the serial number to fetch the vehicle data.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int serialNumber = Integer.parseInt(serialNumberInput); // Convert to integer

        // Find the vehicle in the ArrayList
        EmergencyVehicle vehicleFound = VehicleManager.findVehicleBySerialNumber(serialNumber);

        if (vehicleFound == null) {
            JOptionPane.showMessageDialog(this, "Vehicle not found. Please check the serial number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Populate the input fields with the vehicle's details
        tfSerialNumber.setText(String.valueOf(vehicleFound.getSerialNumber()));
        tfModelNumber.setText(vehicleFound.getModelNumber());
        tfEmergencyVehicleName.setText(vehicleFound.getEmergencyVehicleName());
        cbVehicleType.setSelectedItem(vehicleFound.getVehicleType());
        cbAvailabilityStatus.setSelectedItem(vehicleFound.getAvailabilityStatus());
        cbLocation.setSelectedItem(vehicleFound.getCurrentLocation());
        tfPrice.setText(String.valueOf(vehicleFound.getPrice()));

        // Enable the update button
        btnUpdateVehicle.setEnabled(true);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid serial number. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);    }//GEN-LAST:event_btnFetchActionPerformed
    }

/**
 * Method to sort the vehicle data by serial number.
 * This method sorts the vehicle list by serial number in ascending order, updates the table,
 * and displays a success message.
 *
 * @param evt the action event triggered by the button click
 */
    private void btSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortActionPerformed
 try {
         ArrayList<EmergencyVehicle> sortedVehicles = 
            (ArrayList<EmergencyVehicle>) SelectionSort.sortBySerialNumber(VehicleManager.getEmergencyVehicles(), false);

        // Sort the list in ascending order
        VehicleManager.setEmergencyVehicles(sortedVehicles);

        // Refresh the table to display sorted data (implement `populateVehicleTable`)
        populateVehicleTable();

        // Success message
        JOptionPane.showMessageDialog(this, "Vehicles sorted by Serial Number in ascending order.", "Sort Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (IllegalArgumentException e) {
        // Handle error cases
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btSortActionPerformed

/**
 * Method to add a service request for a vehicle.
 * This method validates the serial number and service request input from the user, checks if the vehicle exists,
 * and updates the service request in the table if all validations pass.
 *
 * @param evt the action event triggered by the button click
 */
 
    private void btnAddServiceRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceRequestActionPerformed
    String serialNumberStr = tfSerialNumber.getText();
    String request = tfServiceRequest.getText();

    // Validation logic
    StringBuilder errorMessages = new StringBuilder();
    int serialNumber = -1;

    if (serialNumberStr == null || serialNumberStr.trim().isEmpty()) {
        errorMessages.append("Serial number cannot be empty.\n");
    } else {
        try {
            serialNumber = Integer.parseInt(serialNumberStr);
            if (serialNumber < 0) {
                errorMessages.append("Serial number must be a positive number.\n");
            }
        } catch (NumberFormatException e) {
            errorMessages.append("Serial number must be a valid number.\n");
        }
    }

    if (request == null || request.trim().isEmpty()) {
        errorMessages.append("Service request cannot be empty.\n");
    } else {
        if (request.length() < 10 || request.length() > 100) {
            errorMessages.append("Service request must be between 10 and 100 characters.\n");
        }
    }

    // If there are validation errors, show them and return
    if (errorMessages.length() > 0) {
        JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Find the row with the specified serial number
    DefaultTableModel tableModel = (DefaultTableModel) tblEmergencyVehicles.getModel();
    boolean serialNumberFound = false;
    for (int i = 0; i < tableModel.getRowCount(); i++) {
        System.out.println("Checking row " + i + ": " + tableModel.getValueAt(i, 0));
        if (serialNumber == 0) {
            JOptionPane.showMessageDialog(null, "Serial number 0 is not present in the table.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (serialNumber == (int) tableModel.getValueAt(i, 0)) { // Assuming column 0 is for serial numbers
            tableModel.setValueAt(request, i, 7); // Assuming column 7 is for service requests
            serialNumberFound = true;
            break;
        }
    }

    if (!serialNumberFound) {
        JOptionPane.showMessageDialog(null, "Serial number not found.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    tfSerialNumber.setText("");  // Clear the input field
    tfServiceRequest.setText("");  // Clear the input field

    JOptionPane.showMessageDialog(null, "Service Request Added Successfully!");

    }//GEN-LAST:event_btnAddServiceRequestActionPerformed

    
 /**
 * Method to update the table with the dispatched vehicle status.
 
 * This method updates the dispatch status of a vehicle in the table based on the vehicle's serial number.
 *
 * @param vehicle the EmergencyVehicle object to update in the table
 */
    private void updateTableWithDispatchedVehicle(EmergencyVehicle vehicle) {
    DefaultTableModel tableModel = (DefaultTableModel) tblEmergencyVehicles.getModel();

    for (int i = 0; i < tableModel.getRowCount(); i++) {
        int serialNumber = (int) tableModel.getValueAt(i, 0); // Assuming column 0 is for serial numbers

        if (serialNumber == vehicle.getSerialNumber()) {
            tableModel.setValueAt("Dispatched", i, 8); // Assuming column 8 is for dispatch status
            break;
        }
    }
}

/**
 * Method to dispatch a vehicle based on the serial number.
 
 * This method validates the serial number input, dispatches the vehicle, updates the table, and displays appropriate messages.
 *
 * @param evt the action event triggered by the button click
 */
  
    private void btnDispatchVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDispatchVehicleActionPerformed
    int serialNumber;
    
    try {
        serialNumber = Integer.parseInt(tfDispatchVehicle.getText()); // Assuming tfSerialNumber is your text field for entering serial numbers
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid serial number.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    EmergencyVehicle vehicle = VehicleManager.findVehicleBySerialNumber(serialNumber);

    if (vehicle != null) {
        VehicleManager.dispatchVehicle(vehicle);  // Dispatch the vehicle
        updateTableWithDispatchedVehicle(vehicle);  // Update the table
        JOptionPane.showMessageDialog(null, "Vehicle dispatched successfully!");
    } else {
        JOptionPane.showMessageDialog(null, "Vehicle not found.", "Error", JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_btnDispatchVehicleActionPerformed
  
  /**
 * Method to sort the vehicle data by model name.
  
 * This method sorts the vehicle list by model name in ascending order, updates the table, and displays a success message.
 *
 * @param evt the action event triggered by the button click
 */   
    private void btnSortByModelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByModelNameActionPerformed
    VehicleManager.setEmergencyVehicles(
        (ArrayList<EmergencyVehicle>) InsertionSort.sortByString(
            VehicleManager.getEmergencyVehicles(),
            false,
            "emergencyVehicleName"
        )
    );

    // Refresh the table to show the sorted data
    populateVehicleTable();
    // Display a confirmation message
    JOptionPane.showMessageDialog(null, "Vehicles sorted by model name in ascending order.","Sort Confirmation", JOptionPane.INFORMATION_MESSAGE);
            }//GEN-LAST:event_btnSortByModelNameActionPerformed

 /**
 * Method to sort the vehicle data by vehicle name using MergeSort.

 * This method sorts the vehicle list by vehicle name in ascending order using MergeSort, updates the table, and displays a success message.
 *
 * @param evt the action event triggered by the button click
 */  
    private void btnSortByVehicleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByVehicleNameActionPerformed
// Sort emergency vehicles by their name in ascending order using MergeSort
    VehicleManager.setEmergencyVehicles(
        new ArrayList<>(
            MergeSort.sortByVehicleName(
                VehicleManager.getEmergencyVehicles(),
                false // Pass 'true' for descending order
            )
        )
    );
      populateVehicleTable();
    
// Display a confirmation message 
JOptionPane.showMessageDialog(null, "Vehicles sorted by vehicle number in ascending order.", "Sort Confirmation", JOptionPane.INFORMATION_MESSAGE);
    // Refresh the table to show the sorted data
    populateVehicleTable();    }//GEN-LAST:event_btnSortByVehicleNameActionPerformed

    private void tfModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModelNumberActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

 /**
 * Method to handle the logout action.
 * This method closes the HomeScreen and reopens the LoginScreen.
 */
    private void logoutAction() {
        // Close the HomeScreen
        dispose();

        // Reopen the LoginScreen
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlServiceRequest;
    private javax.swing.JScrollPane SpAboutus;
    private javax.swing.JTextArea TAAboutUS;
    private javax.swing.JButton btSort;
    private javax.swing.JButton btnAddServiceRequest;
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnDeleteVehicle;
    private javax.swing.JButton btnDispatchVehicle;
    private javax.swing.JButton btnFetch;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSortByModelName;
    private javax.swing.JButton btnSortByVehicleName;
    private javax.swing.JButton btnUpdateVehicle;
    private javax.swing.JComboBox<String> cbAvailabilityStatus;
    private javax.swing.JComboBox<String> cbLocation;
    private javax.swing.JComboBox<String> cbVehicleType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAboutUsLogo;
    private javax.swing.JLabel lblAbouta;
    private javax.swing.JLabel lblAmbulance1;
    private javax.swing.JLabel lblAmbulance2;
    private javax.swing.JLabel lblAmbulanceNumber;
    private javax.swing.JLabel lblAmbulanceNumber1;
    private javax.swing.JLabel lblAmbulanceNumber2;
    private javax.swing.JLabel lblAvailabilityStatus;
    private javax.swing.JLabel lblAvailableAmbulance;
    private javax.swing.JLabel lblAvailableAmbulance1;
    private javax.swing.JLabel lblAvailableAmbulance2;
    private javax.swing.JLabel lblAvailableFire;
    private javax.swing.JLabel lblAvailablePolice1;
    private javax.swing.JLabel lblAvailablePolice2;
    private javax.swing.JLabel lblCurrentLocation;
    private javax.swing.JLabel lblEmergencyVehicleIS;
    private javax.swing.JLabel lblEmergencyVehicleName;
    private javax.swing.JLabel lblFireTruck1;
    private javax.swing.JLabel lblFireTruck2;
    private javax.swing.JLabel lblFirefightersNumber;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblNumberAmbulance;
    private javax.swing.JLabel lblNumberAmbulance1;
    private javax.swing.JLabel lblNumberAmbulance2;
    private javax.swing.JLabel lblNumberFirefightersAvailable;
    private javax.swing.JLabel lblNumberPoliceAvailable;
    private javax.swing.JLabel lblNumberPoliceAvailable1;
    private javax.swing.JLabel lblNumberPoliceCarsAvailable;
    private javax.swing.JLabel lblNumberPoliceCarsAvailable1;
    private javax.swing.JLabel lblPoliceCar1;
    private javax.swing.JLabel lblPoliceCar2;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblSmallLogo;
    private javax.swing.JLabel lblSortingPart;
    private javax.swing.JLabel lblVehicleType;
    private javax.swing.JLabel lnlServiceRequest;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlAmbulance;
    private javax.swing.JPanel pnlAmbulance1;
    private javax.swing.JPanel pnlAmbulance2;
    private javax.swing.JPanel pnlFirefighters;
    private javax.swing.JPanel pnlPoliceCars;
    private javax.swing.JPanel pnlPoliceCars1;
    private javax.swing.JPanel pnlSortingPart;
    private javax.swing.JPanel pnlheader;
    private javax.swing.JPanel pnlhome;
    private javax.swing.JTabbedPane tbAdminDashBoard;
    private javax.swing.JTable tblEmergencyVehicles;
    private javax.swing.JTextField tfDispatchVehicle;
    private javax.swing.JTextArea tfEmail;
    private javax.swing.JTextArea tfEmergencyCalls;
    private javax.swing.JTextField tfEmergencyVehicleName;
    private javax.swing.JTextField tfModelNumber;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSerialNumber;
    private javax.swing.JTextField tfServiceRequest;
    // End of variables declaration//GEN-END:variables
}
