/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.emergencyvehicle.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 * Prayash Rawal LMU ID: 23056551
 */
/**
 * The LoadingScreen class shows a progress bar that updates over time and
 * switches to the LoginScreen once loading is complete.
 */
public class LoadingScreen extends javax.swing.JFrame {

    private Timer timer; // Timer to update progress bar
    private int progress = 0; // Progress value for the loading bar

    /**
     * Creates new form LoadingScreenS
     */
    public LoadingScreen() {
        initComponents();
        this.setTitle("Loading Screen");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        startLoading();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoading = new javax.swing.JPanel();
        lblLoadingImage = new javax.swing.JLabel();
        lblEmergency = new javax.swing.JLabel();
        lblINFORMATIONSYSTEM = new javax.swing.JLabel();
        jProgressBarloading = new javax.swing.JProgressBar();
        lblLoadingScreen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLoading.setBackground(new java.awt.Color(204, 204, 255));
        pnlLoading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoadingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/emergencyvehicle/resources/Actualambulance.png"))); // NOI18N
        pnlLoading.add(lblLoadingImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 360, 270));

        lblEmergency.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEmergency.setForeground(new java.awt.Color(255, 0, 51));
        lblEmergency.setText("Emergency Vehicle ");
        pnlLoading.add(lblEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        lblINFORMATIONSYSTEM.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblINFORMATIONSYSTEM.setText("INFORMATION SYSTEM");
        pnlLoading.add(lblINFORMATIONSYSTEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));
        pnlLoading.add(jProgressBarloading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1010, 20));

        lblLoadingScreen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLoadingScreen.setForeground(new java.awt.Color(255, 255, 255));
        lblLoadingScreen.setText("Loading...");
        pnlLoading.add(lblLoadingScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 110, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Loading...");
        pnlLoading.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, -1, -1));

        jLabel2.setText("jLabel2");
        pnlLoading.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 90, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Starts the loading process by updating the progress bar and label.
     */
    private void startLoading() {
        timer = new Timer(50, new ActionListener() { // Update every 50ms

            @Override
            public void actionPerformed(ActionEvent e) {
                progress += 2; // Increment progress
                jProgressBarloading.setValue(progress); // Set progress bar value
                lblLoadingScreen.setText("Loading... " + progress + "%");

                // Check if loading is complete
                if (progress >= 300) {
                    timer.stop(); // Stop the timer
                    switchToLoginScreen(); // Switch to LoginScreen
                }
            }
        });
        timer.start(); // Start the timer
    }

    // Switch to the LoginScreen
    private void switchToLoginScreen() {
        this.dispose(); // Close the LoadingScreen
        new LoginScreen().setVisible(true); // Open the LoginScreen
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBarloading;
    private javax.swing.JLabel lblEmergency;
    private javax.swing.JLabel lblINFORMATIONSYSTEM;
    private javax.swing.JLabel lblLoadingImage;
    private javax.swing.JLabel lblLoadingScreen;
    private javax.swing.JPanel pnlLoading;
    // End of variables declaration//GEN-END:variables
}
