/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.EmergencyVehicleIS.view;

import com.EmergencyVehicleIS.controller.datastructure.VehicleManager;
import com.EmergencyVehicleIS.util.validationUtil;
import com.EmergencyVehicleIS.model.EmergencyVehicle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
    initComponents(); // Initialize all GUI components
    
    // Set the DefaultTableModel for the table
    DefaultTableModel tableModel = new DefaultTableModel(
        new Object[][]{}, // Initial data (empty)
        new String[]{"Serial Number", "Vehicle Name", "Model Number", "Vehicle Type", "Availability Status", "Current Location", "Price"} // Column names
    );
    TbTable.setModel(tableModel); // Attach the model to the table
    populateVehicleTable(); // Populate the table with vehicle data
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbAdminDashBoard = new javax.swing.JTabbedPane();
        pnlAboutUs = new javax.swing.JPanel();
        SpAboutus = new javax.swing.JScrollPane();
        TAAboutUS = new javax.swing.JTextArea();
        lblAbout = new javax.swing.JLabel();
        lblAbouta = new javax.swing.JLabel();
        pnlhome = new javax.swing.JPanel();
        pnlAmbulance = new javax.swing.JPanel();
        lblNumberAmbulance = new javax.swing.JLabel();
        lblAmbulanceNumber = new javax.swing.JLabel();
        lblAvailableAmbulance = new javax.swing.JLabel();
        lblOfflineAmbulance = new javax.swing.JLabel();
        pnlFirefighters = new javax.swing.JPanel();
        lblNumberFirefightersAvailable = new javax.swing.JLabel();
        lblFirefightersNumber = new javax.swing.JLabel();
        lblAvailableFire = new javax.swing.JLabel();
        lblOfflineFirefighters1 = new javax.swing.JLabel();
        pnlPoliceCars = new javax.swing.JPanel();
        lblNumberPoliceCarsAvailable = new javax.swing.JLabel();
        lblNumberPoliceAvailable = new javax.swing.JLabel();
        lblAvailablePolice1 = new javax.swing.JLabel();
        lblOfflinePolice1 = new javax.swing.JLabel();
        pnlReviews = new javax.swing.JPanel();
        tfReview1 = new javax.swing.JTextField();
        tfReview2 = new javax.swing.JTextField();
        tfReview3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        lblSerialNumber = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        tfSerialNumber = new javax.swing.JTextField();
        lblEmergencyVehicleName = new javax.swing.JLabel();
        lblVehicleType = new javax.swing.JLabel();
        lblAvailabilityStatus = new javax.swing.JLabel();
        lblCurrentLocation = new javax.swing.JLabel();
        lblDispatchedVehicles = new javax.swing.JLabel();
        lblRecentlyDispatched = new javax.swing.JLabel();
        lblServiceRequest = new javax.swing.JLabel();
        tfModelNumber = new javax.swing.JTextField();
        tfEmergencyVehicleName = new javax.swing.JTextField();
        cbVehicleType = new javax.swing.JComboBox<>();
        tfPrice = new javax.swing.JTextField();
        cbAvailabilityStatus = new javax.swing.JComboBox<>();
        tfDispatchedVehicles = new javax.swing.JTextField();
        tfRecentlyDispatched = new javax.swing.JTextField();
        tfServiceRequest = new javax.swing.JTextField();
        btnAddVehicle = new javax.swing.JButton();
        btnDeleteVehicle = new javax.swing.JButton();
        cbLocation = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbTable = new javax.swing.JTable();
        btnUpdateVehicle = new javax.swing.JButton();
        btnFetch = new javax.swing.JButton();
        pnlheader = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblEmergencyVehicleIS = new javax.swing.JLabel();
        lblLogo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbAdminDashBoard.setBackground(new java.awt.Color(51, 255, 51));

        pnlAboutUs.setBackground(new java.awt.Color(0, 0, 0));
        pnlAboutUs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TAAboutUS.setBackground(new java.awt.Color(0, 0, 0));
        TAAboutUS.setColumns(20);
        TAAboutUS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TAAboutUS.setForeground(new java.awt.Color(255, 255, 255));
        TAAboutUS.setRows(5);
        TAAboutUS.setText("\nIn today's fast-paced world, timely and efficient emergency \nresponse can save countless lives.At EVIS, we aim to revolutionize\n the way emergency vehicles operate by providing a cutting-edge, \ncentralized system for managing and monitoring emergency fleet \noperations.With real-time tracking, seamless communication, and \nintelligent dispatching, our platform ensures that emergency vehicles\n reach their destinations faster and more effectively.By leveraging the \nlatest in technology, EVIS plays a critical role in reducing response \ntimes and improving outcomes for emergency situations.\n\nJoin us in creating safer communities through innovation and dedication.");
        SpAboutus.setViewportView(TAAboutUS);

        pnlAboutUs.add(SpAboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 480, 260));

        lblAbout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(255, 255, 0));
        lblAbout.setText("About Us");
        pnlAboutUs.add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 50));

        lblAbouta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAbouta.setForeground(new java.awt.Color(51, 255, 51));
        lblAbouta.setText("Reliable, Innovative, and Swift Emergency Response Solution");
        pnlAboutUs.add(lblAbouta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 530, -1));

        tbAdminDashBoard.addTab("AboutUs", pnlAboutUs);

        pnlhome.setBackground(new java.awt.Color(0, 0, 0));

        pnlAmbulance.setBackground(new java.awt.Color(0, 255, 51));

        lblNumberAmbulance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberAmbulance.setText("Number Of Ambulance");

        lblAmbulanceNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAmbulanceNumber.setText("10");

        lblAvailableAmbulance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailableAmbulance.setText("Available :");

        lblOfflineAmbulance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOfflineAmbulance.setText("Offline :      11");

        javax.swing.GroupLayout pnlAmbulanceLayout = new javax.swing.GroupLayout(pnlAmbulance);
        pnlAmbulance.setLayout(pnlAmbulanceLayout);
        pnlAmbulanceLayout.setHorizontalGroup(
            pnlAmbulanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmbulanceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlAmbulanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOfflineAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAmbulanceLayout.createSequentialGroup()
                        .addComponent(lblAvailableAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAmbulanceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAmbulanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumberAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pnlAmbulanceLayout.setVerticalGroup(
            pnlAmbulanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmbulanceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNumberAmbulance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAmbulanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmbulanceNumber)
                    .addComponent(lblAvailableAmbulance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOfflineAmbulance)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlFirefighters.setBackground(new java.awt.Color(255, 255, 0));

        lblNumberFirefightersAvailable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberFirefightersAvailable.setText("Number Of Firefighters");

        lblFirefightersNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFirefightersNumber.setText("19");

        lblAvailableFire.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailableFire.setText("Available :");

        lblOfflineFirefighters1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOfflineFirefighters1.setText("Offline :      11");

        javax.swing.GroupLayout pnlFirefightersLayout = new javax.swing.GroupLayout(pnlFirefighters);
        pnlFirefighters.setLayout(pnlFirefightersLayout);
        pnlFirefightersLayout.setHorizontalGroup(
            pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirefightersLayout.createSequentialGroup()
                .addGroup(pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFirefightersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumberFirefightersAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFirefightersLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOfflineFirefighters1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFirefightersLayout.createSequentialGroup()
                                .addComponent(lblAvailableFire, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFirefightersNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(114, 114, 114)))
                .addContainerGap())
        );
        pnlFirefightersLayout.setVerticalGroup(
            pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFirefightersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNumberFirefightersAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFirefightersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirefightersNumber)
                    .addComponent(lblAvailableFire))
                .addGap(18, 18, 18)
                .addComponent(lblOfflineFirefighters1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlPoliceCars.setBackground(new java.awt.Color(255, 0, 51));
        pnlPoliceCars.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblNumberPoliceCarsAvailable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberPoliceCarsAvailable.setText("Number Of Police Cars Available");

        lblNumberPoliceAvailable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberPoliceAvailable.setText("20");

        lblAvailablePolice1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAvailablePolice1.setText("Available :");

        lblOfflinePolice1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOfflinePolice1.setText("Offline :      11");

        javax.swing.GroupLayout pnlPoliceCarsLayout = new javax.swing.GroupLayout(pnlPoliceCars);
        pnlPoliceCars.setLayout(pnlPoliceCarsLayout);
        pnlPoliceCarsLayout.setHorizontalGroup(
            pnlPoliceCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPoliceCarsLayout.createSequentialGroup()
                .addComponent(lblNumberPoliceCarsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPoliceCarsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAvailablePolice1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumberPoliceAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(pnlPoliceCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPoliceCarsLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(lblOfflinePolice1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
        pnlPoliceCarsLayout.setVerticalGroup(
            pnlPoliceCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoliceCarsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblNumberPoliceCarsAvailable)
                .addGap(18, 18, 18)
                .addGroup(pnlPoliceCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberPoliceAvailable)
                    .addComponent(lblAvailablePolice1))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(pnlPoliceCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPoliceCarsLayout.createSequentialGroup()
                    .addContainerGap(106, Short.MAX_VALUE)
                    .addComponent(lblOfflinePolice1)
                    .addGap(14, 14, 14)))
        );

        pnlReviews.setBackground(new java.awt.Color(0, 255, 255));

        tfReview1.setBackground(new java.awt.Color(204, 255, 255));
        tfReview1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfReview1.setText("Cut our response times in half! A game-changer");
        tfReview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfReview1ActionPerformed(evt);
            }
        });

        tfReview2.setBackground(new java.awt.Color(204, 255, 255));
        tfReview2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfReview2.setText("Super user-friendly and efficient—our go-to tool.");
        tfReview2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfReview2ActionPerformed(evt);
            }
        });

        tfReview3.setBackground(new java.awt.Color(204, 255, 255));
        tfReview3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfReview3.setText("Reliable and fast, it’s transformed our emergency ops");
        tfReview3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfReview3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Reviews");

        javax.swing.GroupLayout pnlReviewsLayout = new javax.swing.GroupLayout(pnlReviews);
        pnlReviews.setLayout(pnlReviewsLayout);
        pnlReviewsLayout.setHorizontalGroup(
            pnlReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReviewsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfReview3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfReview1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfReview2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlReviewsLayout.setVerticalGroup(
            pnlReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReviewsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfReview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfReview2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfReview3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblSlogan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(0, 255, 0));
        lblSlogan.setText("Responding Fast, Saving Lives");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/courseWork/resources/ambulancelogop.png"))); // NOI18N

        javax.swing.GroupLayout pnlhomeLayout = new javax.swing.GroupLayout(pnlhome);
        pnlhome.setLayout(pnlhomeLayout);
        pnlhomeLayout.setHorizontalGroup(
            pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhomeLayout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(lblSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhomeLayout.createSequentialGroup()
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlReviews, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pnlFirefighters, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addComponent(pnlPoliceCars, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(pnlAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        pnlhomeLayout.setVerticalGroup(
            pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhomeLayout.createSequentialGroup()
                .addComponent(lblSlogan)
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhomeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pnlAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlPoliceCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlFirefighters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhomeLayout.createSequentialGroup()
                        .addComponent(pnlReviews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        tbAdminDashBoard.addTab("Homepage", pnlhome);

        pnlAdmin.setBackground(new java.awt.Color(153, 153, 153));

        lblSerialNumber.setText("Serial Number");

        lblModelNumber.setText("Model Number");

        lblPrice.setText("Price");

        lblEmergencyVehicleName.setText("Emergency Vehicle Name");

        lblVehicleType.setText("Vehicle Type");

        lblAvailabilityStatus.setText("Availability Status");

        lblCurrentLocation.setText("Current Location");

        lblDispatchedVehicles.setText("Dispatched Vehicles");

        lblRecentlyDispatched.setText("Recently Dispatched");

        lblServiceRequest.setText("Service Request");

        cbVehicleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulance", "Fire Truck", "Police Car" }));

        cbAvailabilityStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));

        tfDispatchedVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDispatchedVehiclesActionPerformed(evt);
            }
        });

        tfRecentlyDispatched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRecentlyDispatchedActionPerformed(evt);
            }
        });

        tfServiceRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfServiceRequestActionPerformed(evt);
            }
        });

        btnAddVehicle.setText("Add Vehicle");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        btnDeleteVehicle.setText("Delete Vehicle");
        btnDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVehicleActionPerformed(evt);
            }
        });

        cbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manamaiju", "Kamalpokhari", "Baneshwor", "Ratnapark", "Gongabu", "Basundhara", "Thamel" }));

        TbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "QSRE234", "Falcon23", "Firetruck", "1100", "Available", "Basundhara"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Serial Number", "Model Number", "Vehicle Name", "Vehicle Type", "Price", "Availability Status", "Current Location"
            }
        ));
        jScrollPane1.setViewportView(TbTable);

        btnUpdateVehicle.setText("Update Vehicles");
        btnUpdateVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVehicleActionPerformed(evt);
            }
        });

        btnFetch.setText("Fetch");
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSerialNumber)
                            .addComponent(tfSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(btnAddVehicle)
                        .addGap(59, 59, 59)))
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(lblModelNumber)
                        .addGap(33, 33, 33)
                        .addComponent(lblEmergencyVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFetch))
                        .addGap(48, 48, 48)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateVehicle)
                            .addComponent(tfEmergencyVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVehicleType))
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblAvailabilityStatus)
                                .addGap(30, 30, 30)
                                .addComponent(lblCurrentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbAvailabilityStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDispatchedVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRecentlyDispatched, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblServiceRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(tfDispatchedVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(tfRecentlyDispatched, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfServiceRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(btnDeleteVehicle)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNumber)
                    .addComponent(lblModelNumber)
                    .addComponent(lblEmergencyVehicleName)
                    .addComponent(lblVehicleType)
                    .addComponent(lblPrice)
                    .addComponent(lblAvailabilityStatus)
                    .addComponent(lblCurrentLocation)
                    .addComponent(lblDispatchedVehicles)
                    .addComponent(lblRecentlyDispatched)
                    .addComponent(lblServiceRequest))
                .addGap(18, 18, 18)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfEmergencyVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbAvailabilityStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDispatchedVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfRecentlyDispatched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfServiceRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVehicle)
                    .addComponent(btnUpdateVehicle)
                    .addComponent(btnFetch)
                    .addComponent(btnDeleteVehicle))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        tbAdminDashBoard.addTab("Admin Dashboard", pnlAdmin);

        pnlheader.setBackground(new java.awt.Color(0, 0, 0));

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblEmergencyVehicleIS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEmergencyVehicleIS.setForeground(new java.awt.Color(255, 0, 0));
        lblEmergencyVehicleIS.setText("Emergency Vehicle IS");

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/courseWork/resources/Actualsmallambulance.png"))); // NOI18N

        javax.swing.GroupLayout pnlheaderLayout = new javax.swing.GroupLayout(pnlheader);
        pnlheader.setLayout(pnlheaderLayout);
        pnlheaderLayout.setHorizontalGroup(
            pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303)
                .addComponent(lblEmergencyVehicleIS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        pnlheaderLayout.setVerticalGroup(
            pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
            .addGroup(pnlheaderLayout.createSequentialGroup()
                .addGroup(pnlheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlheaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout))
                    .addGroup(pnlheaderLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblEmergencyVehicleIS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbAdminDashBoard)
            .addComponent(pnlheader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbAdminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
                logoutAction();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tfServiceRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfServiceRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfServiceRequestActionPerformed

    private void tfRecentlyDispatchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRecentlyDispatchedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRecentlyDispatchedActionPerformed

    private void tfDispatchedVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDispatchedVehiclesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDispatchedVehiclesActionPerformed
 
private void populateVehicleTable() {
    // Get the DefaultTableModel from the table
    DefaultTableModel tableModel = (DefaultTableModel) TbTable.getModel();
    tableModel.setRowCount(0); // Clear existing rows
    
    // Add rows to the table using data from the ArrayList
    for (EmergencyVehicle vehicle : VehicleManager.getAllVehicles()) {
        tableModel.addRow(new Object[]{
            vehicle.getSerialNumber(),
            vehicle.getEmergencyVehicleName(),
            vehicle.getModelNumber(),
            vehicle.getVehicleType(),
            vehicle.getAvailabilityStatus(),
            vehicle.getCurrentLocation(),
            vehicle.getPrice()
        });
        System.out.println(VehicleManager.getAllVehicles());

    }
}

// Method to create an EmergencyVehicle object using user inputs and collect all error messages in string builder
private EmergencyVehicle createEmergencyVehicleFromInputs() {
    // Initializing a StringBuilder to collect all error messages
    StringBuilder errorMessages = new StringBuilder();

    // Get inputs from text fields
    String serialNumberText = tfSerialNumber.getText().trim();
    String modelNumber = tfModelNumber.getText().trim();
    String emergencyVehicleName = tfEmergencyVehicleName.getText().trim(); 
    String priceText = tfPrice.getText().trim();

    // Fetch vehicle type from the combo box
    String vehicleType = (String) cbVehicleType.getSelectedItem();

    // Validate vehicle type
    String vehicleTypeError = validationUtil.validateEmergencyVehicleType(cbVehicleType);
    if (vehicleTypeError != null) {
        errorMessages.append(vehicleTypeError).append("\n");
    }

    // Fetch location from the combo box
    String location = (String) cbLocation.getSelectedItem();

    // Validate location
    String locationError = validationUtil.validateLocation(cbLocation);
    if (locationError != null) {
        errorMessages.append(locationError).append("\n");
    }

    // Fetch availability status from the combo box
    String availabilityStatus = (String) cbAvailabilityStatus.getSelectedItem();

    // Validate availability status
    String availabilityStatusError = validationUtil.validateAvailabilityStatus(cbAvailabilityStatus);
    if (availabilityStatusError != null) {
        errorMessages.append(availabilityStatusError).append("\n");
    }

    // Validate serial number
    String serialValidationError = validationUtil.validateSerialNumber(serialNumberText);
    if (serialValidationError != null) {
        errorMessages.append(serialValidationError).append("\n");
    }

    // Validate model number
    String modelNumberError = validationUtil.validateModelNumber(modelNumber);
    if (modelNumberError != null) {
        errorMessages.append(modelNumberError).append("\n");
    }

    // Validate vehicle name
    String vehicleNameError = validationUtil.validateVehicleName(emergencyVehicleName);
    if (vehicleNameError != null) {
        errorMessages.append(vehicleNameError).append("\n");
    }

    // Validate price
    String priceValidationError = validationUtil.validatePrice(priceText);
    if (priceValidationError != null) {
        errorMessages.append("Price: ").append(priceValidationError).append("\n");
    }

    // If there are any validation errors, show all messages and return null
    if (errorMessages.length() > 0) {
        throw new IllegalArgumentException(errorMessages.toString());
    }

    // Parse validated inputs
    int serialNumber = Integer.parseInt(serialNumberText);
    int price = Integer.parseInt(priceText);

    // Create and return the Emergency Vehicle object
    return new EmergencyVehicle(serialNumber, modelNumber, emergencyVehicleName, vehicleType, availabilityStatus, location, price);
}
    
//Method to clear all the textfields and reset the combobox
private void clearInputFields() {
    // Clear all text fields
    tfSerialNumber.setText("");
    tfModelNumber.setText("");
    tfEmergencyVehicleName.setText("");
    tfPrice.setText("");

    // Reset combo boxes to the first item (assuming the first item is a placeholder)
    cbVehicleType.setSelectedIndex(0);  
    cbAvailabilityStatus.setSelectedIndex(0); 
    cbLocation.setSelectedIndex(0);
}

//Method to add the vehicle information in the arrrylist
    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
    // Collect all validation errors at once
    StringBuilder errorMessages = new StringBuilder();

    // Validate emergency vehicle creation inputs
    EmergencyVehicle newVehicle = null; // Initialize the vehicle object
    try {
        newVehicle = createEmergencyVehicleFromInputs();
    } catch (IllegalArgumentException e) {
        // Append the specific error message from createEmergencyVehicleFromInputs
        errorMessages.append(e.getMessage()).append("\n");
    }

    // If there are errors or the vehicle is null, show them and stop execution
    if (errorMessages.length() > 0 || newVehicle == null) {
        JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.WARNING_MESSAGE);
        return; // Stop further execution
    }

    // Check for duplicate serial numbers
    for (EmergencyVehicle ev : VehicleManager.getAllVehicles()) { 
        if (ev.getSerialNumber() == newVehicle.getSerialNumber()) {
            // Append an error message for duplicate serial number
            errorMessages.append("A vehicle with serial number ").append(newVehicle.getSerialNumber()).append(" already exists.\n");
            break; // Exit the loop once a duplicate is found
        }
    }

    // If there are errors after serial number check, show them and stop execution
    if (errorMessages.length() > 0) {
        JOptionPane.showMessageDialog(null, errorMessages.toString(), "Validation Errors", JOptionPane.WARNING_MESSAGE);
        return; // Stop further execution
    }

    // Proceed to add the vehicle only if all validations pass
    try {
        VehicleManager.addVehicle(newVehicle);

        // Clear the input fields after successful addition
        clearInputFields();

        // Optionally, show a success message
        JOptionPane.showMessageDialog(null, "Emergency Vehicle Added Successfully!");
        populateVehicleTable();
    } catch (Exception ex) {
        // Handle unexpected errors during addition
        JOptionPane.showMessageDialog(null, "An error occurred while adding the vehicle: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    
    }    }//GEN-LAST:event_btnAddVehicleActionPerformed



  //Method to delete the vehicle information
    private void btnDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVehicleActionPerformed
    String serialNumberInput = tfSerialNumber.getText().trim(); // Get the input from the user

    if (serialNumberInput.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the serial number.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int serialNumber = Integer.parseInt(serialNumberInput); // Convert to integer

        boolean isDeleted = VehicleManager.deleteVehicle(serialNumber); // Delete vehicle from the ArrayList

        if (isDeleted) {
            // Refresh the table to reflect the deletion
            populateVehicleTable();

            JOptionPane.showMessageDialog(this, "Vehicle deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearInputFields(); // Clear the input fields
        } else {
            JOptionPane.showMessageDialog(this, "Vehicle not found. Please check the serial number.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid serial number. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
    
    }    }//GEN-LAST:event_btnDeleteVehicleActionPerformed

    private void tfReview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfReview1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfReview1ActionPerformed

    private void tfReview2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfReview2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfReview2ActionPerformed

    private void tfReview3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfReview3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfReview3ActionPerformed

    
    // Method to update the vehicle according to the serial number
    private void btnUpdateVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVehicleActionPerformed
try {
        // Validate and create a new EmergencyVehicle object from inputs
        EmergencyVehicle updatedVehicle = createEmergencyVehicleFromInputs();

        // Find and update the vehicle in the ArrayList
        boolean isUpdated = VehicleManager.updateVehicle(updatedVehicle);

        if (isUpdated) {
            // Refresh the table
            populateVehicleTable();

            JOptionPane.showMessageDialog(this, "Vehicle details updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearInputFields(); // Clear the input fields
            btnUpdateVehicle.setEnabled(false); // Disable update button
        } else {
            JOptionPane.showMessageDialog(this, "Vehicle not found. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Validation Errors", JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_btnUpdateVehicleActionPerformed

    
    // Method to fetch the vehicle data to edit 
    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed
    String serialNumberInput = tfSerialNumber.getText().trim(); // Get the serial number input

    if (serialNumberInput.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the serial number to fetch the vehicle data.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int serialNumber = Integer.parseInt(serialNumberInput); // Convert to integer

        // Find the vehicle in the ArrayList
        EmergencyVehicle vehicleFound = VehicleManager.findVehicleBySerialNumber(serialNumber);

        if (vehicleFound == null) {
            JOptionPane.showMessageDialog(this, "Vehicle not found. Please check the serial number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Populate the input fields with the vehicle's details
        tfSerialNumber.setText(String.valueOf(vehicleFound.getSerialNumber()));
        tfModelNumber.setText(vehicleFound.getModelNumber());
        tfEmergencyVehicleName.setText(vehicleFound.getEmergencyVehicleName());
        cbVehicleType.setSelectedItem(vehicleFound.getVehicleType());
        cbAvailabilityStatus.setSelectedItem(vehicleFound.getAvailabilityStatus());
        cbLocation.setSelectedItem(vehicleFound.getCurrentLocation());
        tfPrice.setText(String.valueOf(vehicleFound.getPrice()));

        // Enable the update button
        btnUpdateVehicle.setEnabled(true);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid serial number. Please enter a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);    }//GEN-LAST:event_btnFetchActionPerformed
    }
    
    
    private void logoutAction() {
        // Close the HomeScreen
        dispose();

        // Reopen the LoginScreen
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SpAboutus;
    private javax.swing.JTextArea TAAboutUS;
    private javax.swing.JTable TbTable;
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnDeleteVehicle;
    private javax.swing.JButton btnFetch;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateVehicle;
    private javax.swing.JComboBox<String> cbAvailabilityStatus;
    private javax.swing.JComboBox<String> cbLocation;
    private javax.swing.JComboBox<String> cbVehicleType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAbouta;
    private javax.swing.JLabel lblAmbulanceNumber;
    private javax.swing.JLabel lblAvailabilityStatus;
    private javax.swing.JLabel lblAvailableAmbulance;
    private javax.swing.JLabel lblAvailableFire;
    private javax.swing.JLabel lblAvailablePolice1;
    private javax.swing.JLabel lblCurrentLocation;
    private javax.swing.JLabel lblDispatchedVehicles;
    private javax.swing.JLabel lblEmergencyVehicleIS;
    private javax.swing.JLabel lblEmergencyVehicleName;
    private javax.swing.JLabel lblFirefightersNumber;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblNumberAmbulance;
    private javax.swing.JLabel lblNumberFirefightersAvailable;
    private javax.swing.JLabel lblNumberPoliceAvailable;
    private javax.swing.JLabel lblNumberPoliceCarsAvailable;
    private javax.swing.JLabel lblOfflineAmbulance;
    private javax.swing.JLabel lblOfflineFirefighters1;
    private javax.swing.JLabel lblOfflinePolice1;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRecentlyDispatched;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblServiceRequest;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblVehicleType;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlAmbulance;
    private javax.swing.JPanel pnlFirefighters;
    private javax.swing.JPanel pnlPoliceCars;
    private javax.swing.JPanel pnlReviews;
    private javax.swing.JPanel pnlheader;
    private javax.swing.JPanel pnlhome;
    private javax.swing.JTabbedPane tbAdminDashBoard;
    private javax.swing.JTextField tfDispatchedVehicles;
    private javax.swing.JTextField tfEmergencyVehicleName;
    private javax.swing.JTextField tfModelNumber;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfRecentlyDispatched;
    private javax.swing.JTextField tfReview1;
    private javax.swing.JTextField tfReview2;
    private javax.swing.JTextField tfReview3;
    private javax.swing.JTextField tfSerialNumber;
    private javax.swing.JTextField tfServiceRequest;
    // End of variables declaration//GEN-END:variables
}
